
#================================================
# Warning: You must run DockerBuild.py before
#           running this.
#================================================

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    

    #----------------------------------------------
    app01sq:
    #----------------------------------------------
        image: "app01sq:latest"
        ports:
            - "127.0.0.1:8090:8090"
        
        networks:
            - net
        restart: always


