
# vi:nu:et:sts=4 ts=4 sw=4

# WARNING: This file must be located in the main directory
#           because of docker-compose limitations.

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    

    #----------------------------------------------
    app01sq:
    #----------------------------------------------
        # Run the latest version of our application
        # container passing the appropriate startup
        # parameters such as sql server password.
        image: "app01sq:latest"
        build:
            context: "."
            dockerfile: "./Dockerfile"
        ports:
            - "127.0.0.1:8094:8094"
        
        networks:
            - net
        restart: always


