
#================================================
# Warning: You must run DockerBuild.py before
#           running this.
#================================================

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    #----------------------------------------------
    db:
    #----------------------------------------------
        image: "localhost:2017-latest"
        environment:
            ACCEPT_EULA=Y
            MSSQL_SA_PASSWORD=Passw0rd
            
        expose:
            - "1433"
        networks:
            - net
        restart: always

    #----------------------------------------------
    app01ms:
    #----------------------------------------------
        image: "app01ms:latest"
        ports:
            - "127.0.0.1:8090:8090"
        environment:
            APP01MS_DBSERVER: db
            APP01MS_DBPORT: 1433
        depends_on:
            - db
        networks:
            - net
        restart: always


