
# vi:nu:et:sts=4 ts=4 sw=4

# WARNING: This file must be located in the main directory
#           because of docker-compose limitations.

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    #----------------------------------------------
    db:
    #----------------------------------------------
        # Create and the docker sql server container
        # with the appropriate startup arguments such
        # as root password.
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: "Passw0rd"
            MYSQL_DATABASE: "app01my"
            
        expose:
            - "3306"
        networks:
            - net
        restart: always

    #----------------------------------------------
    app01my:
    #----------------------------------------------
        # Run the latest version of our application
        # container passing the appropriate startup
        # parameters such as sql server password.
        image: "app01my:latest"
        build:
            context: "."
            dockerfile: "./Dockerfile"
        ports:
            - "127.0.0.1:8092:8092"
        environment:
            APP01MY_DB_SERVER: "db"
            APP01MY_DB_PORT: "3306"
        depends_on:
            - db
        networks:
            - net
        restart: always


