
#================================================
# Warning: You must run DockerBuild.py before
#           running this.
#================================================

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    #----------------------------------------------
    db:
    #----------------------------------------------
        image: "localhost:5.7"
        environment:
            MYSQL_ROOT_PASSWORD="Passw0rd"
            MYSQL_DATABASE="app01my"
            
        expose:
            - "3306"
        networks:
            - net
        restart: always

    #----------------------------------------------
    app01my:
    #----------------------------------------------
        image: "app01my:latest"
        ports:
            - "127.0.0.1:8090:8090"
        environment:
            APP01MY_DBSERVER: db
            APP01MY_DBPORT: 3306
        depends_on:
            - db
        networks:
            - net
        restart: always


