
#================================================
# Warning: You must run DockerBuild.py before
#           running this.
#================================================

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    #----------------------------------------------
    db:
    #----------------------------------------------
        image: "localhost:11.3"
        environment:
            POSTGRES_PASSWORD="Passw0rd"
        expose:
            - "5432"
        networks:
            - net
        restart: always

    #----------------------------------------------
    app01pg:
    #----------------------------------------------
        image: "app01pg:latest"
        ports:
            - "127.0.0.1:8090:8090"
        environment:
            APP01PG_DBSERVER: db
            APP01PG_DBPORT: 5432
        depends_on:
            - db
        networks:
            - net
        restart: always


