
# vi:nu:et:sts=4 ts=4 sw=4

version: "3"

#================================================
networks:
#================================================
    net:

#================================================
services:
#================================================

    #----------------------------------------------
    db:
    #----------------------------------------------
        # Create and the docker sql server container
        # with the appropriate startup arguments such
        # as root password.
        image: "postgres:11.3"
        environment:
            POSTGRES_PASSWORD: "Passw0rd"
        expose:
            - "5432"
        networks:
            - net
        restart: always

    #----------------------------------------------
    app01pg:
    #----------------------------------------------
        # Run the latest version of our application
        # container passing the appropriate startup
        # parameters such as sql server password.
        image: "app01pg:latest"
        build:
            context: "."
            dockerfile: "./Dockerfile"
        ports:
            - "127.0.0.1:8093:8093"
        environment:
            APP01PG_DB_SERVER: "db"
            APP01PG_DB_PORT: "5432"
        depends_on:
            - db
        networks:
            - net
        restart: always


